# Generated by Django 4.1.3 on 2022-11-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songapp', '0002_alter_artiste_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
