# Generated by Django 4.1.3 on 2022-11-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songapp', '0003_alter_artiste_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date_released',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
