# Generated by Django 4.1.3 on 2022-11-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songapp', '0004_alter_song_date_released'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist_id',
        ),
    ]
