# Generated by Django 4.1.3 on 2022-11-04 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songapp', '0005_remove_song_artist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyrics',
            name='songs_id',
        ),
        migrations.AddField(
            model_name='song',
            name='artist_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artiste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='songapp.artiste'),
        ),
        migrations.AlterField(
            model_name='song',
            name='date_released',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
