# Generated by Django 4.1.3 on 2022-11-04 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songapp', '0006_remove_lyrics_songs_id_song_artist_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artiste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songapp.artiste'),
        ),
    ]
