# Generated by Django 4.1.3 on 2022-11-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songapp', '0007_alter_song_artiste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist_id',
        ),
    ]
