# Generated by Django 4.1.3 on 2022-11-04 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songapp', '0008_remove_song_artist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artiste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='songapp.artiste'),
        ),
    ]
